### ISSUE TITLE
Position Property "absolute" by default.

### ISSUE THREAD

**Issue by PriyashanJayasankha** [naver/egjs-view360#324]
## Description
I'm using this with angular. but the component is not positioning well in my application. I realize that the issue is Position property is set to "absolute" by default.

`canvas.style.position = "absolute";`

I changed this manually to "static" and my error is fixed. But edition files inside node modules is not a long term solution. Can you fix it ?

**Comment by WoodNeck** [comment]
Hello, @PriyashanJayasankha!
We can't change the default style as many other applications are relying on that style.
I recommend applying additional CSS in your case.
```css
.your-canvas-container-class > canvas {
  position: static !important;
}
```
