### ISSUE TITLE
Change canvas default position to other than absolute

### ISSUE THREAD

**Issue by ssoldy** [naver/egjs-view360#337]
Is there a way to change the canvas position to relative? i wonder why it is absolute by default

**Comment by WoodNeck** [comment]
Hello, @ssoldy!
I think `position: absolute` is used for fitting the canvas full into its wrapper.
If that's making your page ugly, you can easily bypass that by using CSS `!important` directive.
```css
#your-viewer > canvas {
  position: relative !important;
}
```
